force-app/main/default/objects/Case/fields/Sent_Case_Configs__c.field-meta.xml
<CustomField>
    <fullName>Sent_Case_Configs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a checkbox field intended to hold information if the case has sent configs using the case config component.</description>
    <inlineHelpText>Keeps track of the case config sent Status</inlineHelpText>
    <label>Sent Case Configs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <description>This is the object to store the specific configs associated with the case object.</description>
    <label>Case_Config</label>
    <nameField>
        <label>Case_Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This is the field to hold the amount value of the config object. Length is set as 16 and decimal places as 2.</description>
    <inlineHelpText>Amount for the case config.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the lookup relationship linking a case config to the case object.</description>
    <inlineHelpText>Case object assigned the config.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>This is the field to hold the label value of the case config object. It is unique and case insensitive.</description>
    <inlineHelpText>Label of the case config.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the field to hold the type value of the case config object.</description>
    <inlineHelpText>Type of the case config.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <description>This is the object to store the available configs.</description>
    <label>Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This is the field to hold the amount value of the case config object. Length is set as 16 and decimal places as 2.</description>
    <inlineHelpText>Amount of the config.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>This is the field to hold the label value of the config object. It is unique and case insensitive.</description>
    <inlineHelpText>Label of the config.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the field to hold the type value of the config object.</description>
    <inlineHelpText>Type of the config.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AvailableConfigsController.cls
public with sharing class AvailableConfigsController {
    @AuraEnabled(cacheable=true)
    public static List<Config__c> getAvailableConfigs(String field, String sortOrder, Integer queryLimit, Integer queryOffset){
        try {
            String query;
            query  = 'select Id, Label__c, Type__c, Amount__c from Config__c WITH SECURITY_ENFORCED';
            if(field != null && sortOrder !=null){
                query += ' ORDER BY '+field+' '+sortOrder;
            }
            if(queryLimit !=null && queryOffset!=null){
                query +=' limit :queryLimit offset :queryOffset';
            }
            return Database.query(String.escapeSingleQuotes(query));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string saveCaseConfigs(Id caseId, List<Id> configIds){
        String status;
        try {
            Case currentCase = [select Id, Status, Sent_Case_Configs__c from Case where Id =:caseId WITH SECURITY_ENFORCED];
            if(!currentCase.Sent_Case_Configs__c){
                Set<String> requestedLabels = new Set<String>();
                List<Config__c> configList = [select Label__c, Type__c, Amount__c from Config__c WHERE Id in :configIds WITH SECURITY_ENFORCED];
                for(Config__c conf: configList) {
                    requestedLabels.add(conf.Label__c);
                }
                Set<String> existingLabels = getExistingCaseLabels(requestedLabels);
                List<Case_Config__c> newCaseConfigs = getNewCaseConfigs(caseId, configList, existingLabels);
                if(newCaseConfigs.size() > 0){
                    SObjectAccessDecision decision = Security.stripInaccessible(AccessType.CREATABLE, newCaseConfigs);
                    insert decision.getRecords();
                    status = 'Added '+decision.getRecords().size()+' new configs';
                }
                else{
                    status = 'NO_NEW_INSERTS';
                }
            }
            else{
                status = 'CONFIG_ALREADY_SENT';
            }
            return status;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    private static Set<String> getExistingCaseLabels(Set<String> requestedLabels){
        List<Case_Config__c> existingConfigs = [select Label__c from Case_Config__c where Label__c IN: requestedLabels WITH SECURITY_ENFORCED];
        Set<String> existingLabels = new Set<String>();
        for(Case_Config__c caseConf: existingConfigs) {
            existingLabels.add(caseConf.Label__c);
        }
        return existingLabels;
    }
    private static List<Case_Config__c> getNewCaseConfigs(Id caseId, List<Config__c> configList, Set<String> existingLabels){
        List<Case_Config__c> newCaseConfigs = new List<Case_Config__c>();
        for (Config__c conf: configList){
            if(!existingLabels.contains(conf.Label__c)){
                Case_Config__c tempConf = new Case_Config__c();
                tempConf.Label__c = conf.Label__c;
                tempConf.Amount__c = conf.Amount__c;
                tempConf.Type__c = conf.Type__c;
                tempConf.Case__c = caseId;
                newCaseConfigs.add(tempConf);
            }
        }
        return newCaseConfigs;
    }
}