force-app/main/default/objects/Case/fields/Sent_Case_Configs__c.field-meta.xml
<CustomField>
    <fullName>Sent_Case_Configs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is a checkbox field intended to hold information if the case has sent configs using the case config component.</description>
    <inlineHelpText>Keeps track of the case config sent Status</inlineHelpText>
    <label>Sent Case Configs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <description>This is the object to store the available configs.</description>
    <label>Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>This is the field to hold the label value of the config object. It is unique and case insensitive.</description>
    <inlineHelpText>Label of the config.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AvailableConfigsControllerTest.cls
@isTest
public with sharing class AvailableConfigsControllerTest {
    @TestSetup
    static void testLoadData() {
		List<Config__c> configList = Test.loadData(Config__c.sObjectType, 'Testdata_Config');
		System.assertEquals(configList.size(), 104, 'The static resource has 104 entries');
    }
    @isTest
    static void getAvailableConfigsTest() {
        List<Config__c> configList = AvailableConfigsController.getAvailableConfigs('Label__c', 'asc', 5, 0);
        System.assertEquals(configList.size(), 5, 'The getAvailableConfigs function returned 5 entries');
    }
    @isTest
    static void getAvailableConfigsErrorTest() {
        try{
    		AvailableConfigsController.getAvailableConfigs('Label__c', 'ascending', 5, 0);
		}catch (Exception e){
            system.assert(e instanceof AuraHandledException, 'An exception is thrown due to wrong sorting order');
        }
    }
    @isTest
    static void saveCaseConfigsTest() {
        Case test_case = new Case();
        insert test_case;
        List<Config__c> configList = [select Id from Config__c limit 10];
        List<Id> configIds = new List<Id>();
        for(Config__c conf: configList){
            configIds.add(conf.Id);
        }
        string status;
        
        status = AvailableConfigsController.saveCaseConfigs(test_case.id, configIds);
        System.assertEquals(status, 'Added '+configList.size()+' new configs', 'The saveCaseConfigs function successfully saved entries');
        
        status = AvailableConfigsController.saveCaseConfigs(test_case.id, configIds);
        System.assertEquals(status, 'NO_NEW_INSERTS', 'The saveCaseConfigs function informs that no new inserts occured');
        
        test_case.Sent_Case_Configs__c=true;
        update test_case;
        
        status = AvailableConfigsController.saveCaseConfigs(test_case.id, configIds);
        System.assertEquals(status, 'CONFIG_ALREADY_SENT', 'The saveCaseConfigs function informs that the case already has sent configs');
    }
    @isTest
    static void saveCaseConfigsErrorTest() {
        List<Config__c> configList = [select Id from Config__c limit 10];
        List<Id> configIds = new List<Id>();
        for(Config__c conf: configList){
            configIds.add(conf.Id);
        }
        try{
    		AvailableConfigsController.saveCaseConfigs(configIds.get(0), configIds);
		}catch (Exception e){
            system.assert(e instanceof AuraHandledException, 'An exception is thrown due to invalid case Id');
        }
    }
}