force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <description>This is the object to store the specific configs associated with the case object.</description>
    <label>Case_Config</label>
    <nameField>
        <label>Case_Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This is the field to hold the amount value of the config object. Length is set as 16 and decimal places as 2.</description>
    <inlineHelpText>Amount for the case config.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the lookup relationship linking a case config to the case object.</description>
    <inlineHelpText>Case object assigned the config.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>This is the field to hold the label value of the case config object. It is unique and case insensitive.</description>
    <inlineHelpText>Label of the case config.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the field to hold the type value of the case config object.</description>
    <inlineHelpText>Type of the case config.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseConfigsController.cls
public with sharing class CaseConfigsController {
    @AuraEnabled(cacheable=true)
    public static List<Case_Config__c> getCaseConfigs(Id caseId){
        try {
            return [select Id, Label__c, Type__c, Amount__c from Case_Config__c where Case__c =:caseId WITH SECURITY_ENFORCED];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}