force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <description>This is the object to store the specific configs associated with the case object.</description>
    <label>Case_Config</label>
    <nameField>
        <label>Case_Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This is the field to hold the amount value of the config object. Length is set as 16 and decimal places as 2.</description>
    <inlineHelpText>Amount for the case config.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>This is the field to hold the label value of the case config object. It is unique and case insensitive.</description>
    <inlineHelpText>Label of the case config.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the field to hold the type value of the case config object.</description>
    <inlineHelpText>Type of the case config.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseConfigWrapper.cls
public with sharing class CaseConfigWrapper {
    Id caseId;
    String status;
    List<CaseConfigFormatted> caseConfigs;
    public CaseConfigWrapper(Id caseId, String status, List<Case_Config__c> caseConfigs){
        this.caseId = caseId;
        this.status = status;
        List<CaseConfigFormatted> caseConfigsFormatted = new List<CaseConfigFormatted>();
        for( Case_Config__c conf: caseConfigs){
            CaseConfigFormatted tempCaseConf = new CaseConfigFormatted();
            tempCaseConf.label = conf.Label__c;
            tempCaseConf.type = conf.Type__c;
            tempCaseConf.amount = conf.Amount__c;
            caseConfigsFormatted.add(tempCaseConf);
        }
        this.caseConfigs = caseConfigsFormatted;
    }
    class CaseConfigFormatted{
        String label;
        String type;
        Decimal amount;
    }
}