force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <description>This is the object to store the specific configs associated with the case object.</description>
    <label>Case_Config</label>
    <nameField>
        <label>Case_Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This is the field to hold the amount value of the config object. Length is set as 16 and decimal places as 2.</description>
    <inlineHelpText>Amount for the case config.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the lookup relationship linking a case config to the case object.</description>
    <inlineHelpText>Case object assigned the config.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>This is the field to hold the label value of the case config object. It is unique and case insensitive.</description>
    <inlineHelpText>Label of the case config.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the field to hold the type value of the case config object.</description>
    <inlineHelpText>Type of the case config.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <description>This is the object to store the available configs.</description>
    <label>Config</label>
    <nameField>
        <label>Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>This is the field to hold the amount value of the case config object. Length is set as 16 and decimal places as 2.</description>
    <inlineHelpText>Amount of the config.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>This is the field to hold the label value of the config object. It is unique and case insensitive.</description>
    <inlineHelpText>Label of the config.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is the field to hold the type value of the config object.</description>
    <inlineHelpText>Type of the config.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseConfigsControllerTest.cls
@isTest
public with sharing class CaseConfigsControllerTest {
    @TestSetup
    static void testLoadData() {
		List<Config__c> configList = Test.loadData(Config__c.sObjectType, 'Testdata_Config');
		System.assertEquals(configList.size(), 104, 'The static resource has 104 entries');
        
        Case testCase = new Case();
        insert testCase;
        List<Config__c> addConfigList = [select Id from Config__c limit 10];
        List<Id> configIds = new List<Id>();
        for(Config__c conf: addConfigList){
            configIds.add(conf.Id);
        }
        AvailableConfigsController.saveCaseConfigs(testCase.id, configIds);
    }
    @isTest
    static void getCaseConfigsTest() {
        Case testCase = [Select Id from Case limit 1];
		List<Case_Config__c> configList = [select Id from Case_Config__c where Case__c =: testCase.Id];
        
        List<Case_Config__c> caseConfigList = CaseConfigsController.getCaseConfigs(testCase.Id, 'Label__c', 'asc');
        System.assertEquals(caseConfigList.size(), configList.size(), 'The getCaseConfigs function successfully returned entries');
        
    }
    @isTest
    static void getCaseConfigsErrorTest() {
        try{
            Case testCase = [Select Id from Case limit 1];
            List<Case_Config__c> configList = [select Id from Case_Config__c where Case__c =: testCase.Id];
    		CaseConfigsController.getCaseConfigs(testCase.Id, 'Label__c', 'ascending');
		}catch (Exception e){
            system.assert(e instanceof AuraHandledException, 'An exception is thrown due to wrong sorting order');
        }
    }
	@isTest
    static void sendConfigsToExternalTest() {
        Test.setMock(HttpCalloutMock.class, new CaseConfigRemoteMockImpl(200));
        Case testCase = [Select Id from Case limit 1];
        List<Case_Config__c> caseConfigs = [select Id, Label__c, Type__c, Amount__c from Case_Config__c where Case__c =: testCase.Id];
        string status;
        Test.startTest();
        status = CaseConfigsController.sendConfigsToExternal(testCase.Id, caseConfigs);
        System.assertEquals(status, 'SUCCESS', 'The sendConfigsToExternal function successfully sent configs');
        
        status = CaseConfigsController.sendConfigsToExternal(testCase.Id, caseConfigs);
        System.assertEquals(status, 'HAS_SENT', 'The sendConfigsToExternal function informs configs was sent already');
        Test.stopTest();
    }
    @isTest
    static void sendConfigsToExternalErrorTest() {
        try{
    		Test.setMock(HttpCalloutMock.class, new CaseConfigRemoteMockImpl(200));
            List<Case_Config__c> caseConfigs = [select Id, Label__c, Type__c, Amount__c from Case_Config__c limit 10];
            string status;
            Test.startTest();
            status = CaseConfigsController.sendConfigsToExternal(caseConfigs.get(0).Id, caseConfigs);
            Test.stopTest();
		}catch (Exception e){
            system.assert(e instanceof AuraHandledException, 'An exception is thrown due to invalid case Id');
        }
    }
    @isTest
    static void sendConfigsToExternalCallErrorTest() {
        Test.setMock(HttpCalloutMock.class, new CaseConfigRemoteMockImpl(404));
        Case testCase = [Select Id from Case limit 1];
        List<Case_Config__c> caseConfigs = [select Id, Label__c, Type__c, Amount__c from Case_Config__c where Case__c =: testCase.Id];
        string status;
        Test.startTest();
        status = CaseConfigsController.sendConfigsToExternal(testCase.Id, caseConfigs);
        System.assertEquals(status, 'CALLOUT_FAILED', 'The sendConfigsToExternal function informs callout has failed');
        Test.stopTest();
    }
}